# Generated by Django 3.2.14 on 2022-07-21 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=6, verbose_name='标签名称')),
            ],
            options={
                'db_table': 'problem_tag',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('title', models.CharField(max_length=10, verbose_name='题目名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(null=True, verbose_name='最后更新时间')),
                ('source', models.CharField(max_length=12, null=True, verbose_name='题源')),
                ('visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('input_description', models.TextField(verbose_name='输入描述')),
                ('output_description', models.TextField(verbose_name='输出描述')),
                ('samples', models.JSONField(verbose_name='输入输出样例')),
                ('hint', models.TextField(null=True, verbose_name='提示')),
                ('languages', models.CharField(choices=[('Python2', 'Python2'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('GoLang', 'GoLang'), ('JavaScript', 'JavaScript')], max_length=10, verbose_name='问题支持语言')),
                ('template', models.JSONField(blank=True, verbose_name='代码模板')),
                ('time_limit', models.IntegerField(verbose_name='时间限制')),
                ('memory_limit', models.IntegerField(verbose_name='内存限制')),
                ('commit_num', models.BigIntegerField(default=0, verbose_name='提交次数')),
                ('accept_num', models.BigIntegerField(default=0, verbose_name='通过数')),
                ('statistics_info', models.JSONField(default=dict, verbose_name='问题数据')),
                ('difficulty', models.CharField(choices=[('Easy', '简单'), ('Medium', '中等'), ('Hard', '困难')], max_length=6, verbose_name='难度')),
                ('contest', models.ManyToManyField(to='contest.Contest')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='tags', to='problems.ProblemTag')),
            ],
            options={
                'db_table': 'problem',
                'ordering': ['-create_time'],
            },
        ),
    ]
