# Generated by Django 3.2.14 on 2022-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='problems', to='problems.ProblemTag'),
        ),
    ]
