# Generated by Django 3.2.14 on 2022-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('problems', '0002_alter_problem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ManyToManyField(null=True, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=30, verbose_name='题目名称'),
        ),
    ]
