# Generated by Django 3.2.14 on 2022-07-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('problems', '0003_auto_20220721_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ManyToManyField(to='contest.Contest'),
        ),
    ]
