# Generated by Django 3.2.14 on 2022-07-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='contest',
        ),
    ]
