# Generated by Django 3.2.14 on 2022-07-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=models.JSONField(null=True, verbose_name='输入输出样例'),
        ),
    ]
