# Generated by Django 3.2.14 on 2022-07-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=models.JSONField(blank=True, null=True, verbose_name='代码模板'),
        ),
    ]
