# Generated by Django 3.2.14 on 2022-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_problem_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statistics_info',
            field=models.JSONField(default=dict, null=True, verbose_name='问题数据'),
        ),
    ]
