# Generated by Django 3.2.14 on 2022-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_problem_statistics_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=models.JSONField(choices=[('Python2', 'Python2'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('GoLang', 'GoLang'), ('JavaScript', 'JavaScript')], verbose_name='问题支持语言'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=models.JSONField(null=True, verbose_name='代码模板'),
        ),
    ]
