# Generated by Django 3.2.14 on 2022-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_alter_problem_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=models.CharField(choices=[('Python2', 'Python2'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('GoLang', 'GoLang'), ('JavaScript', 'JavaScript')], max_length=100, verbose_name='问题支持语言'),
        ),
    ]
