# Generated by Django 3.2.14 on 2022-07-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_alter_problem_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=models.JSONField(verbose_name='问题支持语言'),
        ),
    ]
